version: "3.7"
services: 
  api: 
    container_name: api
    build: .
    image: flairstech/api:latest
    networks: 
      - net
    depends_on: 
      - db
    links:
      - db
    ports: 
      - "6030:6030"
  db: 
    container_name: db
    build: database/
    image: flairstech/db:latest
    networks: 
      - net
    ports: 
      - "5030:5432"
    volumes: 
      - "database:/var/lib/postgresql/data"
networks: 
  net: 
    name: net
    driver: bridge
volumes: 
  database: {}
