version: "3"
services: 
  api: 
    build: .
    image: api-service
    depends_on: 
      - db
    networks: 
      - net
    ports: 
      - "6030:6030"
  db: 
    build: database/
    image: db-service:latest
    networks: 
      - net
    ports: 
      - "5030:5432"
    volumes: 
      - "database:/var/lib/postgresql/data"
networks: 
  net: 
    driver: bridge
volumes: 
  database: {}
